module.exports = {
  // HTTP Status codes
  HTTP: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503
  },
  
  // Códigos de error de negocio
  ERROR_CODES: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_DNI: 'INVALID_DNI',
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
    SHIPMENT_NOT_FOUND: 'SHIPMENT_NOT_FOUND',
    UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
  },
  
  // Roles
  ROLES: {
    ADMIN: 'ADMIN',
    OPERARIO: 'OPERARIO'
  },
  
  // Estados de envío
  SHIPMENT_STATES: {
    RECIBIDO: 'Recibido',
    EN_VIAJE: 'En Viaje',
    ENTREGADO: 'Entregado'
  },
  
  // Tipos de notificación
  NOTIFICATION_TYPES: {
    SHIPMENT_CREATED: 'SHIPMENT_CREATED',
    SHIPMENT_ON_THE_WAY: 'SHIPMENT_ON_THE_WAY',
    SHIPMENT_DELIVERED: 'SHIPMENT_DELIVERED'
  },

  // Estados de notificación
  NOTIFICATION_STATUS: {
    PENDING: 'PENDIENTE',
    SENT: 'ENVIADO',
    FAILED: 'FALLIDO'
  }
};
